# Generated by Django 6.1.1 on 2026-09-17 17:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Contact person name')),
                ('phone', models.CharField(max_length=20, verbose_name='Contact number')),
                ('party_name', models.CharField(blank=True, max_length=150)),
                ('transport_name', models.CharField(blank=True, max_length=150)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-times_used', 'name'],
                'unique_together': {('name', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_date', models.DateField(default=django.utils.timezone.localdate)),
                ('party_name', models.CharField(max_length=150)),
                ('transport_name', models.CharField(max_length=150)),
                ('bill_series', models.CharField(max_length=20)),
                ('bill_no', models.CharField(max_length=40)),
                ('lr_no', models.CharField(blank=True, max_length=60, verbose_name='LR number')),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FOLLOWED', 'Followed up'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='lrinquiry.contact')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-inquiry_date', '-created_at'],
            },
        ),
    ]
