# Generated by Django 5.0.6 on 2026-09-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrinquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Unsolved'), ('FOLLOWED', 'LR coming'), ('CLOSED', 'Solved')], default='OPEN', max_length=10),
        ),
    ]
