# Generated by Django 5.0.6 on 2026-09-19 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrinquiry', '0002_alter_inquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='bill_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bill date'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='lr_no',
            field=models.CharField(blank=True, max_length=60, verbose_name='Cartoon'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['status'], name='lrinquiry_status_idx'),
        ),
    ]
