# Generated by Django 6.1.1 on 2026-09-17 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Employee code')),
                ('name', models.CharField(max_length=120)),
                ('designation', models.CharField(blank=True, max_length=80)),
                ('department', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Currently employed')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('H', 'Half day'), ('L', 'Paid leave'), ('W', 'Week off')], default='P', max_length=1)),
                ('reason', models.TextField(blank=True, help_text='Filled in whenever the employee is not present.', verbose_name='Reason for absence')),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='attendance.employee')),
            ],
            options={
                'verbose_name_plural': 'Attendance',
                'ordering': ['-date', 'employee__name'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
