# Generated by Django 5.0.6 on 2026-09-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'employee__name'], 'verbose_name_plural': 'LR coming status'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='reason',
            field=models.TextField(blank=True, help_text="Filled in whenever the LR hasn't been received.", verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'LR received'), ('A', 'LR not received'), ('H', 'Partially received'), ('L', 'LR pending'), ('W', 'Not expected')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Party code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(blank=True, null=True, verbose_name='Added on'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=80, verbose_name='Route / area'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, max_length=80, verbose_name='Transport name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Currently tracked'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Party name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact number'),
        ),
    ]
