# Generated by Django 5.0.6 on 2026-09-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_options_alter_attendance_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='reason',
            field=models.TextField(blank=True, help_text="Filled in whenever the LR boy isn't coming.", verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'LR coming'), ('A', 'LR not coming'), ('H', 'Half day'), ('L', 'On leave'), ('W', 'Week off')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='LR boy code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=80, verbose_name='Area covered'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, max_length=80, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Currently active'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=120, verbose_name='LR boy name'),
        ),
    ]
