# Generated by Django 5.0.6 on 2026-09-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_convert_removed_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'LR coming'), ('A', 'LR not coming')], default='P', max_length=1),
        ),
    ]
